#!/usr/bin/env python3


if __name__ == '__main__':
    import hello as h
    import sys

    option = ""
    message = ""

    if len(sys.argv) > 2:
        option = sys.argv[1]
        message = sys.argv[2]
    elif len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
            option = sys.argv[1]
        else:
            message = sys.argv[1]

    message = 'Hello world!'

    try:
        if option == '-m':
            h.multi(message)
        if option == '-h':
            h.hello(message)
        if option == '-r':
            h.random(message)
    except KeyboardInterrupt:
        exit()
